//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRF_Project_URE5FA
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmberEtel
    {
        public int EmberEtelId { get; set; }
        public Nullable<int> EmberFK { get; set; }
        public Nullable<int> EtelFK { get; set; }
    
        public virtual Ember Ember { get; set; }
        public virtual Etelek Etelek { get; set; }
    }
}
