//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRF_Project_URE5FA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ember
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ember()
        {
            this.EmberMozgas = new HashSet<EmberMozgas>();
            this.EmberEtel = new HashSet<EmberEtel>();
        }
    
        public int EmberID { get; set; }
        public string Nev { get; set; }
        public Nullable<int> Kor { get; set; }
        public Nullable<int> Suly_kg { get; set; }
        public Nullable<int> Magassag_cm { get; set; }
        public Nullable<bool> Fiu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmberMozgas> EmberMozgas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmberEtel> EmberEtel { get; set; }
    }
}
