//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRF_Project_URE5FA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Energia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Energia()
        {
            this.Etelek = new HashSet<Etelek>();
        }
    
        public int EnergiaID { get; set; }
        public Nullable<int> KCAL { get; set; }
        public Nullable<int> telitett_zsirsav { get; set; }
        public Nullable<int> szenhidrat { get; set; }
        public Nullable<int> cukor { get; set; }
        public Nullable<int> feherje { get; set; }
        public Nullable<int> so { get; set; }
        public Nullable<int> zsir { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Etelek> Etelek { get; set; }
    }
}
