//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRF_Project_URE5FA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Etelek
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Etelek()
        {
            this.EmberEtel = new HashSet<EmberEtel>();
        }
    
        public int EtelId { get; set; }
        public Nullable<int> KategoriaFK { get; set; }
        public Nullable<int> EnergiaFK { get; set; }
        public string Nev { get; set; }
        public string Szarmazas { get; set; }
        public Nullable<int> Ar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmberEtel> EmberEtel { get; set; }
        public virtual Energia Energia { get; set; }
        public virtual Kategoria Kategoria { get; set; }
    }
}
