//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRF_Project_URE5FA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mozgas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mozgas()
        {
            this.EmberMozgas = new HashSet<EmberMozgas>();
        }
    
        public int MozgasID { get; set; }
        public string Nev { get; set; }
        public Nullable<bool> Szabadteri { get; set; }
        public Nullable<bool> Egyenileg_vegezheto { get; set; }
        public Nullable<int> Heti_ora { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmberMozgas> EmberMozgas { get; set; }
    }
}
